
[server]
enableCORS=false

[browser]
pageTitle = "Título de tu Aplicación"

[theme]
primaryColor = "#E63946"
backgroundColor = "#F1FAEE"
secondaryBackgroundColor = "#A8DADC"
textColor = "#1D3557"
font = "sans serif"

[server]
wideMode = true

[logger]
level = "debug"

[caching]
clearOnLoad = true
